// Mocks generated by Mockito 5.4.6 from annotations
// in tinypng_gui/test/providers/api_key_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tinypng_gui/data/models/api_key_info.dart' as _i4;
import 'package:tinypng_gui/data/models/compression_task.dart' as _i7;
import 'package:tinypng_gui/services/api_key_service.dart' as _i2;
import 'package:tinypng_gui/services/queue_event.dart' as _i6;
import 'package:tinypng_gui/services/queue_service.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ApiKeyService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiKeyService extends _i1.Mock implements _i2.ApiKeyService {
  MockApiKeyService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  List<_i4.ApiKeyInfo> getAllKeys() => (super.noSuchMethod(
        Invocation.method(
          #getAllKeys,
          [],
        ),
        returnValue: <_i4.ApiKeyInfo>[],
      ) as List<_i4.ApiKeyInfo>);

  @override
  _i3.Future<void> setDefaultKey(String? keyId) => (super.noSuchMethod(
        Invocation.method(
          #setDefaultKey,
          [keyId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> addApiKey(
    String? key,
    String? alias,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addApiKey,
          [
            key,
            alias,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> removeApiKey(String? keyId) => (super.noSuchMethod(
        Invocation.method(
          #removeApiKey,
          [keyId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearAllKeys() => (super.noSuchMethod(
        Invocation.method(
          #clearAllKeys,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateApiKey(
    String? keyId, {
    String? alias,
    bool? isDefault,
    _i4.ApiKeyStatus? status,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateApiKey,
          [keyId],
          {
            #alias: alias,
            #isDefault: isDefault,
            #status: status,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> validateKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #validateKey,
          [key],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> updateKeyUsage(
    String? key,
    int? compressionCount,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateKeyUsage,
          [
            key,
            compressionCount,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> refreshAllKeyStatus() => (super.noSuchMethod(
        Invocation.method(
          #refreshAllKeyStatus,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [QueueService].
///
/// See the documentation for Mockito's code generation for more information.
class MockQueueService extends _i1.Mock implements _i5.QueueService {
  MockQueueService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i6.QueueEvent> get events => (super.noSuchMethod(
        Invocation.getter(#events),
        returnValue: _i3.Stream<_i6.QueueEvent>.empty(),
      ) as _i3.Stream<_i6.QueueEvent>);

  @override
  int get pendingCount => (super.noSuchMethod(
        Invocation.getter(#pendingCount),
        returnValue: 0,
      ) as int);

  @override
  int get activeCount => (super.noSuchMethod(
        Invocation.getter(#activeCount),
        returnValue: 0,
      ) as int);

  @override
  _i6.QueueStatus get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i6.QueueStatus.idle,
      ) as _i6.QueueStatus);

  @override
  set concurrentLimit(int? limit) => super.noSuchMethod(
        Invocation.setter(
          #concurrentLimit,
          limit,
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addTask(_i7.CompressionTask? task) => super.noSuchMethod(
        Invocation.method(
          #addTask,
          [task],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addTasks(List<_i7.CompressionTask>? tasks) => super.noSuchMethod(
        Invocation.method(
          #addTasks,
          [tasks],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void start() => super.noSuchMethod(
        Invocation.method(
          #start,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void pause() => super.noSuchMethod(
        Invocation.method(
          #pause,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resume() => super.noSuchMethod(
        Invocation.method(
          #resume,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> stop() => (super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void removeTask(String? taskId) => super.noSuchMethod(
        Invocation.method(
          #removeTask,
          [taskId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clear() => super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
