// Mocks generated by Mockito 5.4.6 from annotations
// in tinypng_gui/test/providers/history_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tinypng_gui/data/models/compression_task.dart' as _i4;
import 'package:tinypng_gui/data/models/history_record.dart' as _i5;
import 'package:tinypng_gui/services/history_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeHistoryStatistics_0 extends _i1.SmartFake
    implements _i2.HistoryStatistics {
  _FakeHistoryStatistics_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [HistoryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHistoryService extends _i1.Mock implements _i2.HistoryService {
  MockHistoryService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> saveFromTask(_i4.CompressionTask? task) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveFromTask,
          [task],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.HistoryRecord>> getHistory({
    int? limit = 100,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHistory,
          [],
          {
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue:
            _i3.Future<List<_i5.HistoryRecord>>.value(<_i5.HistoryRecord>[]),
      ) as _i3.Future<List<_i5.HistoryRecord>>);

  @override
  _i3.Future<int> getTotalCount() => (super.noSuchMethod(
        Invocation.method(
          #getTotalCount,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<void> deleteRecord(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteRecord,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i2.HistoryStatistics computeStatistics(List<_i5.HistoryRecord>? records) =>
      (super.noSuchMethod(
        Invocation.method(
          #computeStatistics,
          [records],
        ),
        returnValue: _FakeHistoryStatistics_0(
          this,
          Invocation.method(
            #computeStatistics,
            [records],
          ),
        ),
      ) as _i2.HistoryStatistics);

  @override
  _i3.Future<_i2.HistoryStatistics> getGlobalStatistics() =>
      (super.noSuchMethod(
        Invocation.method(
          #getGlobalStatistics,
          [],
        ),
        returnValue:
            _i3.Future<_i2.HistoryStatistics>.value(_FakeHistoryStatistics_0(
          this,
          Invocation.method(
            #getGlobalStatistics,
            [],
          ),
        )),
      ) as _i3.Future<_i2.HistoryStatistics>);
}
