// Mocks generated by Mockito 5.4.6 from annotations
// in tinypng_gui/test/providers/queue_status_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tinypng_gui/data/datasources/local/settings_local_data_source.dart'
    as _i7;
import 'package:tinypng_gui/data/models/app_settings.dart' as _i2;
import 'package:tinypng_gui/data/models/compression_task.dart' as _i6;
import 'package:tinypng_gui/services/queue_event.dart' as _i5;
import 'package:tinypng_gui/services/queue_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAppSettings_0 extends _i1.SmartFake implements _i2.AppSettings {
  _FakeAppSettings_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [QueueService].
///
/// See the documentation for Mockito's code generation for more information.
class MockQueueService extends _i1.Mock implements _i3.QueueService {
  MockQueueService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i5.QueueEvent> get events => (super.noSuchMethod(
        Invocation.getter(#events),
        returnValue: _i4.Stream<_i5.QueueEvent>.empty(),
      ) as _i4.Stream<_i5.QueueEvent>);

  @override
  int get pendingCount => (super.noSuchMethod(
        Invocation.getter(#pendingCount),
        returnValue: 0,
      ) as int);

  @override
  int get activeCount => (super.noSuchMethod(
        Invocation.getter(#activeCount),
        returnValue: 0,
      ) as int);

  @override
  _i5.QueueStatus get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i5.QueueStatus.idle,
      ) as _i5.QueueStatus);

  @override
  set concurrentLimit(int? limit) => super.noSuchMethod(
        Invocation.setter(
          #concurrentLimit,
          limit,
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addTask(_i6.CompressionTask? task) => super.noSuchMethod(
        Invocation.method(
          #addTask,
          [task],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addTasks(List<_i6.CompressionTask>? tasks) => super.noSuchMethod(
        Invocation.method(
          #addTasks,
          [tasks],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void start() => super.noSuchMethod(
        Invocation.method(
          #start,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void pause() => super.noSuchMethod(
        Invocation.method(
          #pause,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resume() => super.noSuchMethod(
        Invocation.method(
          #resume,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> stop() => (super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void removeTask(String? taskId) => super.noSuchMethod(
        Invocation.method(
          #removeTask,
          [taskId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clear() => super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SettingsLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsLocalDataSource extends _i1.Mock
    implements _i7.SettingsLocalDataSource {
  MockSettingsLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.AppSettings> getSettings() => (super.noSuchMethod(
        Invocation.method(
          #getSettings,
          [],
        ),
        returnValue: _i4.Future<_i2.AppSettings>.value(_FakeAppSettings_0(
          this,
          Invocation.method(
            #getSettings,
            [],
          ),
        )),
      ) as _i4.Future<_i2.AppSettings>);

  @override
  _i4.Future<void> saveSettings(_i2.AppSettings? settings) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSettings,
          [settings],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearSettings() => (super.noSuchMethod(
        Invocation.method(
          #clearSettings,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
