// Mocks generated by Mockito 5.4.6 from annotations
// in tinypng_gui/test/services/api_key_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tinypng_gui/data/datasources/local/secure_api_key_storage.dart'
    as _i3;
import 'package:tinypng_gui/data/datasources/remote/tinypng_api.dart' as _i6;
import 'package:tinypng_gui/data/models/api_key_info.dart' as _i5;
import 'package:tinypng_gui/data/models/compression_result_data.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCompressionResultData_0 extends _i1.SmartFake
    implements _i2.CompressionResultData {
  _FakeCompressionResultData_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SecureApiKeyStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureApiKeyStorage extends _i1.Mock
    implements _i3.SecureApiKeyStorage {
  MockSecureApiKeyStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveApiKeys(List<_i5.ApiKeyInfo>? apiKeys) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveApiKeys,
          [apiKeys],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.ApiKeyInfo>> getApiKeys() => (super.noSuchMethod(
        Invocation.method(
          #getApiKeys,
          [],
        ),
        returnValue: _i4.Future<List<_i5.ApiKeyInfo>>.value(<_i5.ApiKeyInfo>[]),
      ) as _i4.Future<List<_i5.ApiKeyInfo>>);

  @override
  _i4.Future<void> deleteAllApiKeys() => (super.noSuchMethod(
        Invocation.method(
          #deleteAllApiKeys,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [TinyPngApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockTinyPngApi extends _i1.Mock implements _i6.TinyPngApi {
  MockTinyPngApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void setApiKey(String? apiKey) => super.noSuchMethod(
        Invocation.method(
          #setApiKey,
          [apiKey],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<_i2.CompressionResultData> compressImage(
    _i7.File? file, {
    _i6.ResizeOptions? resize,
    String? targetFormat,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #compressImage,
          [file],
          {
            #resize: resize,
            #targetFormat: targetFormat,
          },
        ),
        returnValue: _i4.Future<_i2.CompressionResultData>.value(
            _FakeCompressionResultData_0(
          this,
          Invocation.method(
            #compressImage,
            [file],
            {
              #resize: resize,
              #targetFormat: targetFormat,
            },
          ),
        )),
      ) as _i4.Future<_i2.CompressionResultData>);

  @override
  _i4.Future<bool> validateApiKey(String? apiKey) => (super.noSuchMethod(
        Invocation.method(
          #validateApiKey,
          [apiKey],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
