// Mocks generated by Mockito 5.4.6 from annotations
// in tinypng_gui/test/services/compression_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:tinypng_gui/data/datasources/local/settings_local_data_source.dart'
    as _i9;
import 'package:tinypng_gui/data/datasources/remote/tinypng_api.dart' as _i4;
import 'package:tinypng_gui/data/models/api_key_info.dart' as _i8;
import 'package:tinypng_gui/data/models/app_settings.dart' as _i3;
import 'package:tinypng_gui/data/models/compression_result_data.dart' as _i2;
import 'package:tinypng_gui/services/api_key_service.dart' as _i7;
import 'package:tinypng_gui/services/file_service.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCompressionResultData_0 extends _i1.SmartFake
    implements _i2.CompressionResultData {
  _FakeCompressionResultData_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAppSettings_1 extends _i1.SmartFake implements _i3.AppSettings {
  _FakeAppSettings_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TinyPngApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockTinyPngApi extends _i1.Mock implements _i4.TinyPngApi {
  MockTinyPngApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void setApiKey(String? apiKey) => super.noSuchMethod(
        Invocation.method(
          #setApiKey,
          [apiKey],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<_i2.CompressionResultData> compressImage(
    _i6.File? file, {
    _i4.ResizeOptions? resize,
    String? targetFormat,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #compressImage,
          [file],
          {
            #resize: resize,
            #targetFormat: targetFormat,
          },
        ),
        returnValue: _i5.Future<_i2.CompressionResultData>.value(
            _FakeCompressionResultData_0(
          this,
          Invocation.method(
            #compressImage,
            [file],
            {
              #resize: resize,
              #targetFormat: targetFormat,
            },
          ),
        )),
      ) as _i5.Future<_i2.CompressionResultData>);

  @override
  _i5.Future<bool> validateApiKey(String? apiKey) => (super.noSuchMethod(
        Invocation.method(
          #validateApiKey,
          [apiKey],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ApiKeyService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiKeyService extends _i1.Mock implements _i7.ApiKeyService {
  MockApiKeyService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  List<_i8.ApiKeyInfo> getAllKeys() => (super.noSuchMethod(
        Invocation.method(
          #getAllKeys,
          [],
        ),
        returnValue: <_i8.ApiKeyInfo>[],
      ) as List<_i8.ApiKeyInfo>);

  @override
  _i5.Future<void> setDefaultKey(String? keyId) => (super.noSuchMethod(
        Invocation.method(
          #setDefaultKey,
          [keyId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addApiKey(
    String? key,
    String? alias,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addApiKey,
          [
            key,
            alias,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeApiKey(String? keyId) => (super.noSuchMethod(
        Invocation.method(
          #removeApiKey,
          [keyId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> clearAllKeys() => (super.noSuchMethod(
        Invocation.method(
          #clearAllKeys,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateApiKey(
    String? keyId, {
    String? alias,
    bool? isDefault,
    _i8.ApiKeyStatus? status,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateApiKey,
          [keyId],
          {
            #alias: alias,
            #isDefault: isDefault,
            #status: status,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> validateKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #validateKey,
          [key],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> updateKeyUsage(
    String? key,
    int? compressionCount,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateKeyUsage,
          [
            key,
            compressionCount,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> refreshAllKeyStatus() => (super.noSuchMethod(
        Invocation.method(
          #refreshAllKeyStatus,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [SettingsLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsLocalDataSource extends _i1.Mock
    implements _i9.SettingsLocalDataSource {
  MockSettingsLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.AppSettings> getSettings() => (super.noSuchMethod(
        Invocation.method(
          #getSettings,
          [],
        ),
        returnValue: _i5.Future<_i3.AppSettings>.value(_FakeAppSettings_1(
          this,
          Invocation.method(
            #getSettings,
            [],
          ),
        )),
      ) as _i5.Future<_i3.AppSettings>);

  @override
  _i5.Future<void> saveSettings(_i3.AppSettings? settings) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSettings,
          [settings],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> clearSettings() => (super.noSuchMethod(
        Invocation.method(
          #clearSettings,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [FileService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFileService extends _i1.Mock implements _i10.FileService {
  MockFileService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool isSupportedImage(String? path) => (super.noSuchMethod(
        Invocation.method(
          #isSupportedImage,
          [path],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<int> getFileSize(String? path) => (super.noSuchMethod(
        Invocation.method(
          #getFileSize,
          [path],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  String getFileSizeString(int? bytes) => (super.noSuchMethod(
        Invocation.method(
          #getFileSizeString,
          [bytes],
        ),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.method(
            #getFileSizeString,
            [bytes],
          ),
        ),
      ) as String);

  @override
  String getOutputPath(
    String? originalPath, {
    String? outputDir,
    String? baseDir,
    bool? overwrite = false,
    String? suffix = '',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOutputPath,
          [originalPath],
          {
            #outputDir: outputDir,
            #baseDir: baseDir,
            #overwrite: overwrite,
            #suffix: suffix,
          },
        ),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.method(
            #getOutputPath,
            [originalPath],
            {
              #outputDir: outputDir,
              #baseDir: baseDir,
              #overwrite: overwrite,
              #suffix: suffix,
            },
          ),
        ),
      ) as String);

  @override
  _i5.Future<void> ensureDirectoryExists(
    String? path, {
    bool? isDirectory = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #ensureDirectoryExists,
          [path],
          {#isDirectory: isDirectory},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> isFile(String? path) => (super.noSuchMethod(
        Invocation.method(
          #isFile,
          [path],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> isDirectory(String? path) => (super.noSuchMethod(
        Invocation.method(
          #isDirectory,
          [path],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}
