// Mocks generated by Mockito 5.4.6 from annotations
// in tinypng_gui/test/services/queue_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tinypng_gui/data/models/compression_task.dart' as _i2;
import 'package:tinypng_gui/services/compression_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCompressionTask_0 extends _i1.SmartFake
    implements _i2.CompressionTask {
  _FakeCompressionTask_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CompressionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCompressionService extends _i1.Mock
    implements _i3.CompressionService {
  MockCompressionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.CompressionTask> compressTask(_i2.CompressionTask? task) =>
      (super.noSuchMethod(
        Invocation.method(
          #compressTask,
          [task],
        ),
        returnValue:
            _i4.Future<_i2.CompressionTask>.value(_FakeCompressionTask_0(
          this,
          Invocation.method(
            #compressTask,
            [task],
          ),
        )),
      ) as _i4.Future<_i2.CompressionTask>);
}
